### ISSUE TITLE
posted_at can't be blank

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/coal#15]
Hi

I have news content_type which has a field posted_at which is required: true

In my data/news.yml file, all the news have a posted_at: field filled in with data of this type

```
posted_at: '2015-11-11 18:00:00 +0100'
```

When pushing to the Engine, with the latest version of Coal (locomotivecms_coal (~> 1.0.0.rc3)) and Wagon (locomotivecms_wagon (2.0.0.rc5)), I get the error below.

This error did not occur with the previous versions.

```
Resource invalid: posted_at can't be blank, formatted_posted_at can't be blank
Resource invalid: posted_at can't be blank, formatted_posted_at can't be blank
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_coal-1.0.0.rc3/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_coal-1.0.0.rc3/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_coal-1.0.0.rc3/lib/locomotive/coal/resources/base.rb:35:in `update_with_locale'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:42:in `persist'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:12:in `block in _push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `each'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `_push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:47:in `instrument'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_command.rb:54:in `block in _push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_command.rb:82:in `block in each_resource'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_command.rb:75:in `each'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_command.rb:75:in `each_resource'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_command.rb:53:in `_push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_command.rb:40:in `push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/commands/push_command.rb:30:in `push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon.rb:73:in `push'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/lib/locomotive/wagon/cli.rb:313:in `deploy'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc5/bin/wagon:12:in `<top (required)>'
  /Users/cedriclor/.rbenv/versions/2.2.3/bin/wagon:23:in `load'
  /Users/cedriclor/.rbenv/versions/2.2.3/bin/wagon:23:in `<main>'
```

**Comment by CedricLor** [comment]
Temporary work around.

Define posted_at as required: false in the content_type/news.yml file

**Comment by CedricLor** [comment]
More details because the issue occurs also with other fields. The issue occurs when both required: true and localized: true

However, you would expect that providing localized versions of the field would solve the issue. This is not the case.

I have an event content_type which has a category field defined as follows:

```
category: # The lowercase, underscored name of the field
    label: Category of the event. This will be displayed on the events lists page. # Human readable name of the field
    type: select
    select_options:
      en: ["Dance", "Theater", "Poetry", "Performance"]
      fr: ["Danse", "Théatre", "Poésie", "Performance"]
      ru: ["танец", "Театр", "", "поэзия", "Представление"]
      "zh-CN": ["舞蹈", "剧院", "诗", "性能"]
    required: true
    localized: true
```

In my data/event.yml file, I define my events as follows:

```
"Sample 1":
    description: "Odio ad eaque voluptate aut amet earum et. Nihil necessitatibus excepturi fugiat veritatis et ut. Atque blanditiis suscipit mollitia rerum voluptas id eum. Aliquid voluptas qui."
    location: "Paris, Théâtre National du Palais de Chaillot"
    category:
      en: 'Dance'
      fr: 'Danse'
      ru: 'танец'
      "zh-CN": "舞蹈"
    main_star: Alexeï Guerman
    event_date: 2015/12/03 # YYYY/MM/DD
    event_start_date: 2015/12/24
    event_end_date: 2015/12/28
    featured_image: null # Path to a file in the public/samples folder or to a remote and external file.
```

and I get the same error.

The only work around consists in turning either required or localized as false. 

However, if localized is turned as false, then it won't take my localized category subentries in the various locals from the data/events.yml file.
